```
(catch +callable_term ?term +callable_term)
```

> Enable recovery from exceptions

`(catch Goal Catcher Handler)` behaves as [call/1](#call) if no exception is raised when executing `Goal`. If an exception is raised using [throw/1](#throw) while Goal executes, and the `Goal` is the innermost goal for which `Catcher` unifies with the argument of [throw/1](#throw), all choice points generated by `Goal` are cut, the system backtracks to the start of [catch/3](#catch) while preserving the thrown exception term, and `Handler` is called as in [call/1](#call).